name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '22.17.0'
  PNPM_VERSION: '10.12.4'
  DEBUG_MESSAGE: ${{ secrets.PREVIEW_DEBUG_MESSAGE }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: next lint && pnpm exec prisma validate
        env:
          DEBUG_MESSAGE: ${{ secrets.PREVIEW_DEBUG_MESSAGE }}

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: pnpm run format

  type-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: pnpm exec prisma generate # for type-check
      - run: pnpm velite build --debug # for type-check
      - run: pnpm run type-check
